#! /bin/sh -e

# Copyright (C) 2019 Tomoyuki Fujimori <moyu@dromozoa.com>
#
# This file is part of dromozoa-fuse.
#
# dromozoa-fuse is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# dromozoa-fuse is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with dromozoa-fuse.  If not, see <http://www.gnu.org/licenses/>.

dromozoa_umount() {
  if fusermount -V >/dev/null 2>&1
  then
    fusermount -u "$1"
  else
    umount "$1"
  fi
}

fuse_script=$1
shift
test_script=$1
shift
mount_point=$1
shift

mkdir -p "$mount_point"

case X$# in
  X0) lua "$fuse_script" "$mount_point" -d -s &;;
  *) "$@" "$fuse_script" "$mount_point" -d -s &;;
esac
pid=$!

sleep 1

if "$test_script" "$mount_point"
then
  test_result=OK
else
  test_result=NG
fi

sleep 1

dromozoa_umount "$mount_point"

if wait "$pid"
then
  fuse_result=OK
else
  fuse_result=NG
fi

rmdir "$mount_point"

result=$fuse_result/$test_result
echo "$result"
case X$result in
  XOK/OK) ;;
  *) exit 1;;
esac
